Created before and after save event when saving customer and customer address.
craftcms/commerce pull request #1821
Opened 2020-10-28 10:57 UTC by pdaleramirez

(#1220)

2020-10-28 11:16 UTC, nfourtythree requested changes

2020-10-28 11:16 UTC, nfourtythree commented on src/events/CustomerAddressEvent.php
> + * @since 2.0
@pdaleramirez since tag should be `3.x`

2020-10-28 11:16 UTC, nfourtythree commented on src/events/CustomerEvent.php
> + * @since 2.0
@pdaleramirez since tag should be `3.x`

2020-10-28 11:16 UTC, nfourtythree commented on src/services/Customers.php
> +    const EVENT_BEFORE_SAVE_CUSTOMER = 'beforeSaveCustomer';
@pdaleramirez should add `@since` tags to all the new constants

2020-10-29 05:48 UTC, pdaleramirez reviewed
Made changes

2020-10-29 10:28 UTC, merged

2020-10-29 10:29 UTC, lukeholder commented
Thanks @pdaleramirez