Added pdfChroot setting on dompdf
craftcms/commerce pull request #1844
Opened 2020-11-03 08:18 UTC by pdaleramirez

(#1761)

2020-11-04 15:00 UTC, lukeholder requested changes

2020-11-04 15:00 UTC, lukeholder commented on src/services/Pdfs.php
> +     *    Pdfs::EVENT_ADD_RENDER_OPTIONS,
Rename to `EVENT_MODIFY_RENDER_OPTIONS`

2020-11-05 07:08 UTC, pdaleramirez commented on src/services/Pdfs.php
> +     *    Pdfs::EVENT_ADD_RENDER_OPTIONS,
Done renaming the event name

2020-11-05 13:36 UTC, nfourtythree approved these changes
This all looks good to me, as long as the event is not cancellable which it doesn't look like it is 👍

2020-11-09 05:55 UTC, merged

2020-11-09 05:55 UTC, lukeholder commented
Thanks!