Added refundTransaction object to `\craft\commerce\services\Payments::EVENT_AFTER_CAPTURE_TRANSACTION` event
craftcms/commerce pull request #2082
Opened 2021-04-12 08:55 UTC by pdaleramirez

Fixed (#2081 )

2021-04-28 10:36 UTC, lukeholder requested changes

2021-04-28 10:36 UTC, lukeholder commented on CHANGELOG.md
> +- Added refundTransaction object to `\craft\commerce\services\Payments::EVENT_AFTER_CAPTURE_TRANSACTION` event. ([#2081](https://github.com/craftcms/commerce/issues/2081))
is this the `EVENT_AFTER_CAPTURE_TRANSACTION` or `EVENT_AFTER_REFUND_TRANSACTION`?

2021-04-29 09:35 UTC, nfourtythree requested changes

2021-04-29 09:35 UTC, nfourtythree commented on src/events/TransactionEvent.php
> +    public $refundTransaction;
@pdaleramirez should this attribute only be added to the `RefundTransactionEvent` rather than the `TransactionEvent`?

2021-05-03 12:35 UTC, merged